Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y python3
    sudo apt-get install -y python3-pip
    sudo apt-get install -y libpq-dev
    sudo -H pip3 install psycopg2-binary
    sudo -H pip3 install django
  SHELL

  # Синхронизация файла с хост-машины на виртуальную машину
  config.vm.synced_folder "F:/SyncFolderForVagrant", "/home/vagrant/synced"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end